[package]
name = "auto-table-core"
description = "Core library of auto-table: runtime support and error types for the #[auto_table] / #[auto_create] macros"
version.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
sea-orm.workspace = true
inventory.workspace = true
thiserror.workspace = true
auto-table-derive.workspace = true
