//! Core library for automatic table creation
//!
//! Provides the base types and collection mechanism required by the
//! `#[auto_table]` macro.
//!
//! Error layering: as a reusable library, it exposes a precise
//! [`TableError`] via `thiserror`, so upper layers (applications /
//! macro-generated code) can absorb and propagate it with `anyhow` or a
//! custom error type.

use sea_orm::sea_query::TableCreateStatement;
use sea_orm::{DatabaseConnection, DbBackend};

/// Errors related to automatic table creation (precise library-level error type)
///
/// The public API of the library returns this type so callers can `match`
/// on it to distinguish failure causes; upper application layers can
/// propagate it as `anyhow::Error` via `?`.
#[derive(Debug, thiserror::Error)]
pub enum TableError {
    /// Failed to query the list of existing tables (underlying database error)
    #[error("failed to query existing tables: {0}")]
    QueryExistingFailed(#[from] sea_orm::DbErr),
    /// Failed to create a table (carries the table name for easy diagnosis)
    #[error("failed to create table `{table}`: {source}")]
    CreateFailed {
        /// The name of the table that failed
        table: String,
        /// Underlying database error
        #[source]
        source: sea_orm::DbErr,
    },
    /// Unsupported database backend
    #[error("unsupported database backend: {0:?}")]
    UnsupportedBackend(DbBackend),
}

/// Wrapper structure used for inventory collection
///
/// Every Entity marked with `#[auto_table]` generates an instance of this
/// type, which `inventory` collects automatically at compile time.
pub struct TableRegistration {
    pub create_fn: fn(DbBackend) -> TableCreateStatement,
}

// Collect all registered tables via inventory
inventory::collect!(TableRegistration);

/// Returns the table-creation statements of all registered tables
pub fn get_all_table_statements(backend: DbBackend) -> Vec<TableCreateStatement> {
    inventory::iter::<TableRegistration>
        .into_iter()
        .map(|reg| (reg.create_fn)(backend))
        .collect()
}

/// Extracts the table name from a `TableCreateStatement`
pub fn get_table_name(stmt: &TableCreateStatement) -> Option<String> {
    stmt.get_table_name()
        .map(|table_ref| table_ref.sea_orm_table().to_string())
}

/// Queries the list of existing table names in the database
///
/// Returns [`TableError::UnsupportedBackend`] for unsupported database backends.
///
/// Notes on backend-specific queries:
/// - PostgreSQL: only tables in the `public` schema are returned.
/// - SQLite: `sqlite_master` may also contain internal tables created by
///   SQLite itself (e.g. `sqlite_sequence` when AUTOINCREMENT is used).
pub async fn get_existing_tables(
    db: &DatabaseConnection,
    backend: DbBackend,
) -> Result<Vec<String>, TableError> {
    use sea_orm::ConnectionTrait;

    let sql = match backend {
        DbBackend::MySql => {
            "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE()"
        }
        DbBackend::Postgres => {
            "SELECT tablename FROM pg_tables WHERE schemaname = 'public'"
        }
        DbBackend::Sqlite => {
            "SELECT name FROM sqlite_master WHERE type='table'"
        }
        other => return Err(TableError::UnsupportedBackend(other)),
    };

    let result: Vec<sea_orm::QueryResult> = db
        .query_all_raw(sea_orm::Statement::from_string(backend, sql.to_string()))
        .await?;

    // Rows whose table name cannot be parsed are silently skipped
    let tables = result
        .iter()
        .filter_map(|row| row.try_get_by_index::<String>(0).ok())
        .collect();

    Ok(tables)
}

/// Report of a table-creation run
///
/// Returned by [`create_missing_tables`] (and by the function generated by
/// the `#[auto_create]` macro), so the caller can log the result or perform
/// further operations.
#[derive(Debug, Clone, Default)]
pub struct TableCreationReport {
    /// Registered tables that already existed and were therefore skipped
    pub existing_tables: Vec<String>,
    /// Tables that were newly created in this run
    pub created_tables: Vec<String>,
}

/// Creates all registered tables that do not exist yet in the database
///
/// Queries the existing tables once, then creates every registered table that
/// is missing. No logging is performed; the caller receives a
/// [`TableCreationReport`] describing which tables already existed and which
/// were created, and can log or react to it as needed.
pub async fn create_missing_tables(
    db: &DatabaseConnection,
) -> Result<TableCreationReport, TableError> {
    use sea_orm::ConnectionTrait;

    let backend = db.get_database_backend();
    let statements = get_all_table_statements(backend);
    let existing_tables = get_existing_tables(db, backend).await?;

    let mut report = TableCreationReport::default();

    for mut stmt in statements {
        let table_name = get_table_name(&stmt);

        // Skip tables that already exist and record them
        if let Some(ref name) = table_name {
            if existing_tables.contains(name) {
                report.existing_tables.push(name.clone());
                continue;
            }
        }

        stmt.if_not_exists();
        db.execute(&stmt)
            .await
            .map_err(|source| TableError::CreateFailed {
                table: table_name
                    .clone()
                    .unwrap_or_else(|| "unknown".to_string()),
                source,
            })?;

        // Record the table created in this run
        if let Some(name) = table_name {
            report.created_tables.push(name);
        }
    }

    Ok(report)
}

// Re-export the procedural macros so users only need to depend on the
// `auto_table_core` crate to use both `#[auto_table]` and `#[auto_create]`
// (no separate dependency on `auto_table_derive` required).
pub use auto_table_derive::{auto_create, auto_table};
