//! Parses the CREATE TABLE statements produced by sea-query
//!
//! The expected structure of a table is only available as generated SQL:
//! [`sea_query::TableCreateStatement`] keeps its columns, indexes and
//! constraints in `pub(crate)` fields, so they cannot be read directly. This
//! module turns the generated statement back into a [`TableSchema`].
//!
//! The parser only has to cope with what sea-query emits, which is a far
//! smaller and more regular language than arbitrary DDL. It is written to be
//! tolerant: unrecognized table-level items are skipped rather than failing the
//! whole statement.

use crate::schema::{unquote_literal, ColumnSchema, IndexSchema, TableSchema};

/// Name MySQL reports for the primary key in `INFORMATION_SCHEMA.STATISTICS`
///
/// sea-query gives the primary key constraint its own generated name (such as
/// `pk-sample_memberships`), but the database always reports it as `PRIMARY`.
/// Using this constant keeps both sides of a diff comparable.
pub const PRIMARY_INDEX_NAME: &str = "PRIMARY";

/// Types spelled with more than one word, longest first so that the most
/// specific match wins
const MULTI_WORD_TYPES: [&str; 6] = [
    "timestamp without time zone",
    "timestamp with time zone",
    "time without time zone",
    "time with time zone",
    "character varying",
    "double precision",
];

/// Words that start a table-level item rather than a column definition
const CONSTRAINT_KEYWORDS: [&str; 7] = [
    "primary", "constraint", "unique", "key", "index", "foreign", "check",
];

/// Reserved words that can never be a constraint name
const RESERVED_WORDS: [&str; 7] = [
    "primary", "unique", "key", "index", "constraint", "foreign", "check",
];

/// Keywords that terminate a `DEFAULT <value>` expression
const DEFAULT_TERMINATORS: [&str; 8] = [
    "NOT NULL",
    "PRIMARY KEY",
    "UNIQUE",
    "AUTO_INCREMENT",
    "AUTOINCREMENT",
    "GENERATED BY DEFAULT AS IDENTITY",
    "GENERATED ALWAYS AS IDENTITY",
    "NULL",
];

/// Reasons a generated statement could not be parsed
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum ParseError {
    /// The statement does not start with `CREATE TABLE`
    #[error("not a CREATE TABLE statement")]
    NotCreateTable,
    /// The table name is missing or empty
    #[error("missing table name in the CREATE TABLE statement")]
    MissingTableName,
    /// The parentheses around the column list are unbalanced
    #[error("unbalanced parentheses in the CREATE TABLE statement")]
    UnbalancedParens,
}

/// Parses a generated `CREATE TABLE` statement into a [`TableSchema`]
///
/// Handles the output of all three backends: MySQL quotes identifiers with
/// backticks, PostgreSQL and SQLite with double quotes.
pub fn parse_create_table(sql: &str) -> Result<TableSchema, ParseError> {
    let sql = sql.trim();

    let body_and_name = strip_prefix_ignore_case(sql, "CREATE TABLE IF NOT EXISTS ")
        .or_else(|| strip_prefix_ignore_case(sql, "CREATE TABLE "))
        .ok_or(ParseError::NotCreateTable)?;

    let open = body_and_name
        .find('(')
        .ok_or(ParseError::UnbalancedParens)?;
    let name = unquote_identifier(body_and_name[..open].trim());
    if name.is_empty() {
        return Err(ParseError::MissingTableName);
    }

    let after_open = &body_and_name[open + 1..];
    let close = after_open
        .rfind(')')
        .ok_or(ParseError::UnbalancedParens)?;
    let body = &after_open[..close];

    let mut columns = Vec::new();
    let mut indexes = Vec::new();

    for item in split_top_level(body) {
        if is_table_constraint(item) {
            indexes.extend(parse_table_constraint(item));
            continue;
        }
        if let Some((column, column_indexes)) = parse_column(item) {
            indexes.extend(column_indexes);
            columns.push(column);
        }
    }

    Ok(TableSchema {
        name,
        columns,
        indexes,
    })
}

/// Splits the column list on top-level commas
///
/// A naive `split(',')` breaks on the comma inside `decimal(10,2)`, and on
/// commas inside quoted default values, so both bracket depth and quotes are
/// tracked.
fn split_top_level(body: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut depth = 0i32;
    let mut quote: Option<char> = None;
    let mut start = 0usize;

    for (i, ch) in body.char_indices() {
        if let Some(open) = quote {
            if ch == open {
                quote = None;
            }
            continue;
        }
        match ch {
            '\'' | '"' | '`' => quote = Some(ch),
            '(' => depth += 1,
            ')' => depth -= 1,
            ',' if depth == 0 => {
                out.push(body[start..i].trim());
                start = i + 1;
            }
            _ => {}
        }
    }
    if start < body.len() {
        out.push(body[start..].trim());
    }

    out.retain(|item| !item.is_empty());
    out
}

/// Whether an item of the column list is a table-level constraint
fn is_table_constraint(item: &str) -> bool {
    let Some((first, _)) = split_first_token(item) else {
        return false;
    };
    let lowered = first.to_ascii_lowercase();
    CONSTRAINT_KEYWORDS.contains(&lowered.as_str())
}

/// Parses one column definition, plus the indexes implied by its constraints
fn parse_column(item: &str) -> Option<(ColumnSchema, Vec<IndexSchema>)> {
    let (raw_name, rest) = split_first_token(item)?;
    let name = unquote_identifier(raw_name);
    if name.is_empty() {
        return None;
    }

    let (col_type, flags_src) = split_type(rest);
    let flags = parse_column_flags(&flags_src);

    let mut indexes = Vec::new();
    if flags.primary_key {
        indexes.push(IndexSchema {
            name: PRIMARY_INDEX_NAME.to_string(),
            columns: vec![name.clone()],
            unique: true,
            primary: true,
        });
    }
    if flags.unique {
        // MySQL names a single-column unique index after the column itself,
        // which is what INFORMATION_SCHEMA.STATISTICS reports.
        indexes.push(IndexSchema {
            name: name.clone(),
            columns: vec![name.clone()],
            unique: true,
            primary: false,
        });
    }

    let column = ColumnSchema {
        name,
        col_type,
        nullable: flags.nullable,
        default: flags.default,
        auto_increment: flags.auto_increment,
    };

    Some((column, indexes))
}

/// Parses a table-level `PRIMARY KEY` / `UNIQUE` constraint into an index
///
/// Returns `None` for constraint kinds that are not tracked (foreign keys,
/// checks, ...) so that they are simply skipped.
fn parse_table_constraint(item: &str) -> Option<IndexSchema> {
    let upper = item.to_ascii_uppercase();
    let is_primary = upper.contains("PRIMARY KEY");
    let is_unique = has_word(&upper, "UNIQUE");

    if !is_primary && !is_unique {
        return None;
    }

    let columns = extract_paren_columns(item)?;
    if columns.is_empty() {
        return None;
    }

    if is_primary {
        return Some(IndexSchema {
            name: PRIMARY_INDEX_NAME.to_string(),
            columns,
            unique: true,
            primary: true,
        });
    }

    let name = extract_constraint_name(item).unwrap_or_else(|| columns.join("_"));
    Some(IndexSchema {
        name,
        columns,
        unique: true,
        primary: false,
    })
}

/// The constraints and modifiers that follow a column type
#[derive(Debug, Default)]
struct ColumnFlags {
    nullable: bool,
    default: Option<String>,
    auto_increment: bool,
    primary_key: bool,
    unique: bool,
}

fn parse_column_flags(src: &str) -> ColumnFlags {
    let upper = src.to_ascii_uppercase();

    let mut flags = ColumnFlags {
        nullable: true,
        ..Default::default()
    };

    flags.primary_key = upper.contains("PRIMARY KEY");
    flags.unique = has_word(&upper, "UNIQUE");
    flags.nullable = !upper.contains("NOT NULL");
    flags.auto_increment = upper.contains("AUTO_INCREMENT")
        || upper.contains("AUTOINCREMENT")
        || upper.contains("AS IDENTITY");

    // The identity clause is removed first: PostgreSQL spells it
    // `GENERATED BY DEFAULT AS IDENTITY`, and that DEFAULT is not a column
    // default value.
    flags.default = extract_default(&strip_identity_clause(src));

    flags
}

/// Splits `<type> <flags...>` at the end of the type
fn split_type(s: &str) -> (String, String) {
    let s = s.trim();
    let lower = s.to_ascii_lowercase();

    for multi in MULTI_WORD_TYPES {
        if let Some(rest) = lower.strip_prefix(multi) {
            if rest.is_empty() || rest.starts_with(char::is_whitespace) {
                return (
                    s[..multi.len()].to_string(),
                    s[multi.len()..].trim().to_string(),
                );
            }
        }
    }

    let end = s.find(char::is_whitespace).unwrap_or(s.len());
    (s[..end].to_string(), s[end..].trim().to_string())
}

/// Removes a PostgreSQL `GENERATED ... AS IDENTITY` clause
fn strip_identity_clause(src: &str) -> String {
    let upper = src.to_ascii_uppercase();
    let Some(generated) = upper.find("GENERATED") else {
        return src.to_string();
    };
    let Some(identity) = upper[generated..].find("IDENTITY") else {
        return src.to_string();
    };
    let end = generated + identity + "IDENTITY".len();

    let mut out = String::with_capacity(src.len());
    out.push_str(&src[..generated]);
    out.push(' ');
    out.push_str(src[end..].trim_start());
    out
}

/// Extracts the value of a `DEFAULT` clause, if the column has one
fn extract_default(src: &str) -> Option<String> {
    let upper = src.to_ascii_uppercase();
    let mut start = 0;

    while let Some(relative) = upper[start..].find("DEFAULT") {
        let index = start + relative;
        let after_index = index + "DEFAULT".len();

        let before_is_boundary =
            index == 0 || !upper.as_bytes()[index - 1].is_ascii_alphanumeric();
        let after_is_boundary = after_index >= upper.len()
            || !upper.as_bytes()[after_index].is_ascii_alphanumeric();

        if before_is_boundary && after_is_boundary {
            let rest = src[after_index..].trim();
            let (value, _) = split_at_default_terminator(rest);
            let value = unquote_literal(value.trim());
            return (!value.is_empty()).then_some(value);
        }

        start = after_index;
    }

    None
}

/// Cuts a default value off at the first following keyword
fn split_at_default_terminator(value: &str) -> (&str, &str) {
    let upper = value.to_ascii_uppercase();
    let mut cut = value.len();

    for terminator in DEFAULT_TERMINATORS {
        let mut search = 0;
        while let Some(relative) = upper[search..].find(terminator) {
            let index = search + relative;
            let after_index = index + terminator.len();

            let before_is_boundary =
                index == 0 || !upper.as_bytes()[index - 1].is_ascii_alphanumeric();
            let after_is_boundary = after_index >= upper.len()
                || !upper.as_bytes()[after_index].is_ascii_alphanumeric();

            if before_is_boundary && after_is_boundary && index < cut {
                cut = index;
                break;
            }
            search = after_index;
        }
    }

    value.split_at(cut)
}

/// Whether `word` appears in `upper` as a whole word
fn has_word(upper: &str, word: &str) -> bool {
    let mut search = 0;
    while let Some(relative) = upper[search..].find(word) {
        let index = search + relative;
        let after_index = index + word.len();

        let before_is_boundary =
            index == 0 || !upper.as_bytes()[index - 1].is_ascii_alphanumeric();
        let after_is_boundary =
            after_index >= upper.len() || !upper.as_bytes()[after_index].is_ascii_alphanumeric();

        if before_is_boundary && after_is_boundary {
            return true;
        }
        search = after_index;
    }
    false
}

/// Splits the first whitespace- or quote-delimited token off `s`
fn split_first_token(s: &str) -> Option<(&str, &str)> {
    let s = s.trim();
    let mut bytes = s.bytes();
    let first = bytes.next()?;

    if matches!(first, b'`' | b'"' | b'\'') {
        let close = first as char;
        let end = s[1..].find(close)? + 1;
        return Some((&s[1..end], s[end + 1..].trim_start()));
    }
    if first == b'[' {
        let end = s.find(']')?;
        return Some((&s[1..end], s[end + 1..].trim_start()));
    }

    let end = s.find(char::is_whitespace).unwrap_or(s.len());
    Some((&s[..end], s[end..].trim_start()))
}

/// Strips the surrounding quotes from an identifier
fn unquote_identifier(s: &str) -> String {
    let s = s.trim();
    let bytes = s.as_bytes();
    if bytes.len() >= 2 {
        let matches = matches!(
            (bytes[0], bytes[bytes.len() - 1]),
            (b'`', b'`') | (b'"', b'"') | (b'\'', b'\'') | (b'[', b']')
        );
        if matches {
            return s[1..s.len() - 1].trim().to_string();
        }
    }
    s.to_string()
}

/// Case-insensitive `strip_prefix`
fn strip_prefix_ignore_case<'a>(s: &'a str, prefix: &str) -> Option<&'a str> {
    if s.len() >= prefix.len() && s[..prefix.len()].eq_ignore_ascii_case(prefix) {
        Some(&s[prefix.len()..])
    } else {
        None
    }
}

/// Extracts the column list from a parenthesized constraint, e.g. `(a, b)`
fn extract_paren_columns(item: &str) -> Option<Vec<String>> {
    let open = item.find('(')?;
    let close = item.rfind(')')?;
    if close < open {
        return None;
    }

    let columns = item[open + 1..close]
        .split(',')
        .map(|column| unquote_identifier(column.trim()))
        .filter(|column| !column.is_empty())
        .collect();

    Some(columns)
}

/// Extracts the name of a named constraint, if the statement provides one
///
/// Both spellings are handled: the standard `CONSTRAINT "name" ...` and the
/// MySQL-specific `PRIMARY KEY \`name\` (...)` / `UNIQUE KEY \`name\` (...)`,
/// where the name follows the constraint keyword.
fn extract_constraint_name(item: &str) -> Option<String> {
    let upper = item.to_ascii_uppercase();

    if let Some(relative) = upper.find("CONSTRAINT") {
        let after = item[relative + "CONSTRAINT".len()..].trim_start();
        if let Some((raw, _)) = split_first_token(after) {
            let name = unquote_identifier(raw);
            if !name.is_empty() && !is_reserved(&name) {
                return Some(name);
            }
        }
    }

    if let Some(relative) = upper.find("UNIQUE") {
        let mut after = item[relative + "UNIQUE".len()..].trim_start();
        let after_upper = after.to_ascii_uppercase();
        for keyword in ["KEY ", "INDEX "] {
            if after_upper.starts_with(keyword) {
                after = after[keyword.len()..].trim_start();
                break;
            }
        }
        if let Some((raw, _)) = split_first_token(after) {
            let name = unquote_identifier(raw);
            if !name.is_empty() && !is_reserved(&name) {
                return Some(name);
            }
        }
    }

    None
}

fn is_reserved(word: &str) -> bool {
    RESERVED_WORDS
        .iter()
        .any(|reserved| word.eq_ignore_ascii_case(reserved))
}

#[cfg(test)]
mod tests {
    use super::*;

    // The statements below are copied verbatim from the output of
    // `cargo run --example dump_create_table`.

    const MYSQL_USERS: &str = "CREATE TABLE `sample_users` ( `id` int NOT NULL PRIMARY KEY AUTO_INCREMENT, `email` varchar(255) NOT NULL UNIQUE, `nickname` varchar(255), `age` int NOT NULL, `score` bigint NOT NULL, `balance` decimal NOT NULL, `active` bool NOT NULL, `created_at` timestamp NOT NULL )";

    const MYSQL_MEMBERSHIPS: &str = "CREATE TABLE `sample_memberships` ( `user_id` int NOT NULL, `group_id` int NOT NULL, `role` varchar(255) NOT NULL DEFAULT 'member', `note` varchar(255), PRIMARY KEY `pk-sample_memberships` (`user_id`, `group_id`) )";

    const POSTGRES_USERS: &str = "CREATE TABLE \"sample_users\" ( \"id\" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY, \"email\" varchar NOT NULL UNIQUE, \"nickname\" varchar, \"age\" integer NOT NULL, \"score\" bigint NOT NULL, \"balance\" decimal NOT NULL, \"active\" bool NOT NULL, \"created_at\" timestamp with time zone NOT NULL )";

    const POSTGRES_MEMBERSHIPS: &str = "CREATE TABLE \"sample_memberships\" ( \"user_id\" integer NOT NULL, \"group_id\" integer NOT NULL, \"role\" varchar NOT NULL DEFAULT 'member', \"note\" varchar, CONSTRAINT \"pk-sample_memberships\" PRIMARY KEY (\"user_id\", \"group_id\") )";

    #[test]
    fn parses_mysql_single_primary_key() {
        let schema = parse_create_table(MYSQL_USERS).unwrap();

        assert_eq!(schema.name, "sample_users");
        assert_eq!(schema.columns.len(), 8);

        assert_eq!(
            schema.columns[0],
            ColumnSchema {
                name: "id".into(),
                col_type: "int".into(),
                nullable: false,
                default: None,
                auto_increment: true,
            }
        );
        // An optional column is reported as nullable
        assert_eq!(
            schema.columns[2],
            ColumnSchema {
                name: "nickname".into(),
                col_type: "varchar(255)".into(),
                nullable: true,
                default: None,
                auto_increment: false,
            }
        );
    }

    #[test]
    fn lifts_inline_unique_and_primary_key_into_indexes() {
        let schema = parse_create_table(MYSQL_USERS).unwrap();

        let primary = schema
            .indexes
            .iter()
            .find(|index| index.primary)
            .expect("primary key index");
        assert_eq!(primary.name, "PRIMARY");
        assert_eq!(primary.columns, vec!["id"]);
        assert!(primary.unique);

        // MySQL names a single-column unique index after the column
        let unique = schema
            .indexes
            .iter()
            .find(|index| !index.primary)
            .expect("unique index");
        assert_eq!(unique.name, "email");
        assert_eq!(unique.columns, vec!["email"]);
        assert!(unique.unique);
        assert!(!unique.primary);
    }

    #[test]
    fn parses_mysql_composite_primary_key() {
        let schema = parse_create_table(MYSQL_MEMBERSHIPS).unwrap();

        assert_eq!(schema.name, "sample_memberships");
        // The table-level constraint must not be mistaken for a column
        assert_eq!(schema.columns.len(), 4);
        assert_eq!(schema.columns[0].name, "user_id");
        assert_eq!(schema.columns[1].name, "group_id");

        let primary = schema
            .indexes
            .iter()
            .find(|index| index.primary)
            .expect("composite primary key");
        assert_eq!(primary.name, "PRIMARY");
        assert_eq!(primary.columns, vec!["user_id", "group_id"]);
    }

    #[test]
    fn parses_default_value() {
        let schema = parse_create_table(MYSQL_MEMBERSHIPS).unwrap();

        let role = &schema.columns[2];
        assert_eq!(role.name, "role");
        assert_eq!(role.default.as_deref(), Some("member"));
    }

    #[test]
    fn parses_postgres_multi_word_type() {
        let schema = parse_create_table(POSTGRES_USERS).unwrap();

        let created_at = schema
            .columns
            .iter()
            .find(|column| column.name == "created_at")
            .expect("created_at column");
        assert_eq!(created_at.col_type, "timestamp with time zone");
    }

    #[test]
    fn identity_clause_is_not_a_default_value() {
        let schema = parse_create_table(POSTGRES_USERS).unwrap();

        let id = &schema.columns[0];
        assert_eq!(id.name, "id");
        // `GENERATED BY DEFAULT AS IDENTITY` must not be read as a default
        assert_eq!(id.default, None);
        assert!(id.auto_increment);
        assert!(!id.nullable);
    }

    #[test]
    fn parses_postgres_composite_primary_key() {
        let schema = parse_create_table(POSTGRES_MEMBERSHIPS).unwrap();

        assert_eq!(schema.columns.len(), 4);
        let primary = schema
            .indexes
            .iter()
            .find(|index| index.primary)
            .expect("composite primary key");
        assert_eq!(primary.columns, vec!["user_id", "group_id"]);
    }

    #[test]
    fn keeps_commas_inside_type_precision() {
        // A naive split would cut `decimal(10,2)` in half
        let sql = "CREATE TABLE `t` ( `amount` decimal(10,2) NOT NULL, `name` varchar(255) )";
        let schema = parse_create_table(sql).unwrap();

        assert_eq!(schema.columns.len(), 2);
        assert_eq!(schema.columns[0].col_type, "decimal(10,2)");
        assert_eq!(schema.columns[1].name, "name");
    }

    #[test]
    fn skips_untracked_constraints() {
        let sql = "CREATE TABLE `t` ( `id` int NOT NULL PRIMARY KEY, `age` int NOT NULL, CHECK (`age` > 0) )";
        let schema = parse_create_table(sql).unwrap();

        assert_eq!(schema.columns.len(), 2);
        assert_eq!(schema.indexes.len(), 1, "only the primary key is tracked");
    }

    #[test]
    fn accepts_if_not_exists() {
        let sql = "CREATE TABLE IF NOT EXISTS `t` ( `id` int NOT NULL PRIMARY KEY )";
        let schema = parse_create_table(sql).unwrap();

        assert_eq!(schema.name, "t");
        assert_eq!(schema.columns.len(), 1);
    }

    #[test]
    fn rejects_non_create_table_statements() {
        assert_eq!(
            parse_create_table("SELECT 1"),
            Err(ParseError::NotCreateTable)
        );
        assert_eq!(
            parse_create_table("CREATE TABLE `t` `id` int"),
            Err(ParseError::UnbalancedParens)
        );
        assert_eq!(
            parse_create_table("CREATE TABLE  ( `id` int )"),
            Err(ParseError::MissingTableName)
        );
    }

    /// Parses a statement that sea-query generates *right now*
    ///
    /// The tests above assert against recorded snapshots, which stay green even
    /// if sea-query changes the SQL it emits. This one generates the statement
    /// live, so a change in the generated format fails here and tells us the
    /// parser needs updating.
    mod round_trip {
        use sea_orm::entity::prelude::*;
        use sea_orm::{DbBackend, Schema};

        use crate::parse::parse_create_table;

        #[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
        #[sea_orm(table_name = "round_trip")]
        pub struct Model {
            #[sea_orm(primary_key, auto_increment = true)]
            pub id: i32,
            #[sea_orm(unique)]
            pub email: String,
            pub nickname: Option<String>,
            pub active: bool,
        }

        #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
        pub enum Relation {}

        impl ActiveModelBehavior for ActiveModel {}

        #[test]
        fn parses_what_sea_query_generates_for_mysql() {
            let backend = DbBackend::MySql;
            let statement = Schema::new(backend).create_table_from_entity(Entity);
            let sql = backend.build(&statement).sql;

            let schema = parse_create_table(&sql).expect("generated statement must parse");

            assert_eq!(schema.name, "round_trip");
            assert_eq!(schema.columns.len(), 4);

            let id = &schema.columns[0];
            assert_eq!(id.name, "id");
            assert!(id.auto_increment, "primary key is auto-incremented");
            assert!(!id.nullable);

            assert!(
                schema.columns[2].nullable,
                "an Option<String> column is nullable"
            );
            assert_eq!(schema.columns[3].col_type, "bool", "a bool stays bool");

            assert!(
                schema.indexes.iter().any(|index| index.primary),
                "the primary key is reported as an index"
            );
            assert!(
                schema
                    .indexes
                    .iter()
                    .any(|index| index.name == "email" && index.unique),
                "the unique column is reported as an index"
            );
        }
    }
}
